import type {
  CommandHistoryEntry,
  DataToolHistoryEntry,
  DeskItem,
  UiSettings,
} from '../types/items'

export interface ReleaseDemoSnapshot {
  items: DeskItem[]
  commandHistory: CommandHistoryEntry[]
  dataToolHistory: DataToolHistoryEntry[]
  uiSettings: UiSettings
}

const tableCounts = {
  items: 15,
  item_tags: 31,
  workflow_steps: 9,
  app_settings: 6,
  command_history: 6,
}

export const RELEASE_DEMO_SNAPSHOT: ReleaseDemoSnapshot = {
  items: [
    {
      id: 'app-vscode',
      name: 'VS Code',
      type: 'app',
      description: '主力代码编辑器',
      tags: ['daily', 'frontend', 'backend'],
      icon: '',
      favorite: true,
      createdAt: '2026-03-20T09:00:00.000Z',
      updatedAt: '2026-03-28T08:40:00.000Z',
      lastLaunchedAt: '2026-03-28T08:58:00.000Z',
      launchTarget: 'C:\\Program Files\\Microsoft VS Code\\Code.exe',
    },
    {
      id: 'app-terminal',
      name: 'Windows Terminal',
      type: 'app',
      description: '统一命令行入口',
      tags: ['daily', 'ops'],
      icon: '',
      favorite: true,
      createdAt: '2026-03-20T09:05:00.000Z',
      updatedAt: '2026-03-28T08:30:00.000Z',
      lastLaunchedAt: '2026-03-28T08:54:00.000Z',
      launchTarget: 'C:\\Users\\realfeeling1\\AppData\\Local\\Microsoft\\WindowsApps\\wt.exe',
    },
    {
      id: 'app-figma',
      name: 'Figma',
      type: 'app',
      description: '设计与验收协作',
      tags: ['design', 'team'],
      icon: '',
      favorite: false,
      createdAt: '2026-03-20T09:10:00.000Z',
      updatedAt: '2026-03-27T18:10:00.000Z',
      lastLaunchedAt: '2026-03-27T11:20:00.000Z',
      launchTarget: 'C:\\Users\\realfeeling1\\AppData\\Local\\Figma\\Figma.exe',
    },
    {
      id: 'project-deskhub',
      name: 'DeskHub Desktop',
      type: 'project',
      description: 'Tauri + React 桌面控制台主仓库',
      tags: ['frontend', 'tauri', 'release'],
      icon: '',
      favorite: true,
      createdAt: '2026-03-20T10:00:00.000Z',
      updatedAt: '2026-03-28T09:02:00.000Z',
      lastLaunchedAt: '2026-03-28T09:00:00.000Z',
      projectPath: 'C:\\Users\\realfeeling1\\DeskHub',
      devCommand: 'npm run tauri:dev',
    },
    {
      id: 'project-api',
      name: 'Gateway API',
      type: 'project',
      description: '统一认证与数据聚合服务',
      tags: ['backend', 'api'],
      icon: '',
      favorite: false,
      createdAt: '2026-03-20T10:10:00.000Z',
      updatedAt: '2026-03-27T15:20:00.000Z',
      lastLaunchedAt: '2026-03-27T09:10:00.000Z',
      projectPath: 'D:\\Workspaces\\gateway-api',
      devCommand: 'pnpm dev',
    },
    {
      id: 'project-docs',
      name: 'Docs Portal',
      type: 'project',
      description: '产品文档与发布说明站点',
      tags: ['docs', 'frontend'],
      icon: '',
      favorite: false,
      createdAt: '2026-03-20T10:20:00.000Z',
      updatedAt: '2026-03-26T18:00:00.000Z',
      lastLaunchedAt: '2026-03-26T13:00:00.000Z',
      projectPath: 'D:\\Workspaces\\docs-portal',
      devCommand: 'pnpm docs:dev',
    },
    {
      id: 'url-github',
      name: 'GitHub',
      type: 'url',
      description: '代码托管与 issue 协作',
      tags: ['docs', 'team'],
      icon: '',
      favorite: true,
      createdAt: '2026-03-20T11:00:00.000Z',
      updatedAt: '2026-03-27T12:00:00.000Z',
      lastLaunchedAt: '2026-03-28T08:42:00.000Z',
      url: 'https://github.com',
    },
    {
      id: 'url-linear',
      name: 'Linear',
      type: 'url',
      description: '需求与迭代跟踪',
      tags: ['team', 'planning'],
      icon: '',
      favorite: true,
      createdAt: '2026-03-20T11:10:00.000Z',
      updatedAt: '2026-03-28T08:20:00.000Z',
      lastLaunchedAt: '2026-03-28T08:45:00.000Z',
      url: 'https://linear.app',
    },
    {
      id: 'url-notion',
      name: 'Notion',
      type: 'url',
      description: '笔记、文档与会议纪要',
      tags: ['docs', 'team'],
      icon: '',
      favorite: false,
      createdAt: '2026-03-20T11:20:00.000Z',
      updatedAt: '2026-03-27T16:30:00.000Z',
      lastLaunchedAt: '2026-03-27T16:32:00.000Z',
      url: 'https://www.notion.so',
    },
    {
      id: 'folder-assets',
      name: 'Design Assets',
      type: 'folder',
      description: '图标、截图与发布素材',
      tags: ['design', 'release'],
      icon: '',
      favorite: false,
      createdAt: '2026-03-20T12:00:00.000Z',
      updatedAt: '2026-03-27T17:00:00.000Z',
      lastLaunchedAt: '2026-03-27T17:40:00.000Z',
      path: 'D:\\Assets\\DeskHub',
    },
    {
      id: 'folder-workspace',
      name: 'Client Workspace',
      type: 'folder',
      description: '多项目工作区入口',
      tags: ['daily', 'workspace'],
      icon: '',
      favorite: false,
      createdAt: '2026-03-20T12:10:00.000Z',
      updatedAt: '2026-03-26T15:00:00.000Z',
      lastLaunchedAt: '2026-03-26T15:10:00.000Z',
      path: 'D:\\Workspaces',
    },
    {
      id: 'script-build',
      name: '发布前检查',
      type: 'script',
      description: '运行 lint、测试与 build',
      tags: ['release', 'ops'],
      icon: '',
      favorite: true,
      createdAt: '2026-03-20T13:00:00.000Z',
      updatedAt: '2026-03-28T08:50:00.000Z',
      lastLaunchedAt: '2026-03-28T08:51:00.000Z',
      command: 'npm run check',
      executionMode: 'new_terminal',
    },
    {
      id: 'script-clean',
      name: '清理缓存',
      type: 'script',
      description: '清理临时构建与日志缓存',
      tags: ['ops', 'maintenance'],
      icon: '',
      favorite: false,
      createdAt: '2026-03-20T13:10:00.000Z',
      updatedAt: '2026-03-26T09:30:00.000Z',
      lastLaunchedAt: null,
      command: 'pnpm clean:temp',
      executionMode: 'background',
    },
    {
      id: 'workflow-focus',
      name: '一键上班模式',
      type: 'workflow',
      description: '打开主项目、启动终端并拉起协作站点',
      tags: ['daily', 'workflow', 'focus'],
      icon: '',
      favorite: true,
      createdAt: '2026-03-20T14:00:00.000Z',
      updatedAt: '2026-03-28T09:05:00.000Z',
      lastLaunchedAt: '2026-03-28T09:03:00.000Z',
      variables: [
        {
          id: 'var-branch',
          key: 'branch',
          label: '分支名',
          defaultValue: 'main',
          required: false,
        },
      ],
      steps: [
        {
          id: 'workflow-focus-step-1',
          type: 'open_path',
          path: 'C:\\Users\\realfeeling1\\DeskHub',
          note: '打开主项目目录',
          delayMs: 0,
          condition: null,
        },
        {
          id: 'workflow-focus-step-2',
          type: 'run_command',
          command: 'npm run tauri:dev',
          executionMode: 'new_terminal',
          failureStrategy: 'stop',
          retryCount: 1,
          retryDelayMs: 1000,
          note: '启动桌面调试',
          delayMs: 0,
          condition: null,
        },
        {
          id: 'workflow-focus-step-3',
          type: 'open_url',
          url: 'https://github.com',
          note: '打开代码托管',
          delayMs: 200,
          condition: null,
        },
        {
          id: 'workflow-focus-step-4',
          type: 'open_url',
          url: 'https://linear.app',
          note: '打开排期面板',
          delayMs: 200,
          condition: null,
        },
      ],
    },
    {
      id: 'workflow-release',
      name: '发版流程',
      type: 'workflow',
      description: '检查版本、构建应用并打开发布文档',
      tags: ['release', 'workflow'],
      icon: '',
      favorite: false,
      createdAt: '2026-03-20T14:10:00.000Z',
      updatedAt: '2026-03-27T21:15:00.000Z',
      lastLaunchedAt: '2026-03-27T21:20:00.000Z',
      variables: [],
      steps: [
        {
          id: 'workflow-release-step-1',
          type: 'run_command',
          command: 'npm run check',
          executionMode: 'new_terminal',
          failureStrategy: 'stop',
          retryCount: 1,
          retryDelayMs: 1000,
          note: '校验质量门',
          delayMs: 0,
          condition: null,
        },
        {
          id: 'workflow-release-step-2',
          type: 'run_command',
          command: 'npm run tauri:build',
          executionMode: 'new_terminal',
          failureStrategy: 'continue',
          retryCount: 1,
          retryDelayMs: 1000,
          note: '生成安装包',
          delayMs: 0,
          condition: null,
        },
        {
          id: 'workflow-release-step-3',
          type: 'open_url',
          url: 'https://github.com/realfeeling1/DeskHub/releases',
          note: '打开 Release 页面',
          delayMs: 200,
          condition: null,
        },
      ],
    },
  ],
  commandHistory: [
    {
      kind: 'item',
      target: 'workflow-focus',
      title: '一键上班模式',
      lastUsedAt: '2026-03-28T09:03:20.000Z',
      useCount: 11,
    },
    {
      kind: 'item',
      target: 'project-deskhub',
      title: 'DeskHub Desktop',
      lastUsedAt: '2026-03-28T09:00:10.000Z',
      useCount: 9,
    },
    {
      kind: 'action',
      target: 'open_data_tools',
      title: '打开数据工具',
      lastUsedAt: '2026-03-28T08:57:00.000Z',
      useCount: 7,
    },
    {
      kind: 'route',
      target: '/projects',
      title: '项目',
      lastUsedAt: '2026-03-28T08:56:30.000Z',
      useCount: 6,
    },
    {
      kind: 'route',
      target: '/workflows',
      title: '工作流',
      lastUsedAt: '2026-03-28T08:55:00.000Z',
      useCount: 5,
    },
    {
      kind: 'item',
      target: 'url-linear',
      title: 'Linear',
      lastUsedAt: '2026-03-28T08:45:10.000Z',
      useCount: 4,
    },
  ],
  dataToolHistory: [
    {
      id: 'history-backup',
      action: 'backup',
      status: 'success',
      title: '数据库备份完成',
      summary: '已导出最新 deskhub.db 备份，可用于升级前回滚。',
      occurredAt: '2026-03-28T08:20:00.000Z',
      outputPath: 'C:\\Users\\realfeeling1\\Documents\\DeskHub\\deskhub-2026-03-28.db',
      backupPath: '',
      itemNames: ['DeskHub Desktop', '一键上班模式'],
      errors: [],
      extra: {
        schemaVersion: 6,
        itemCount: 15,
        workflowCount: 2,
        quickCheck: 'ok',
        foreignKeysEnabled: true,
        tableCounts,
      },
    },
    {
      id: 'history-health',
      action: 'health_check',
      status: 'success',
      title: '数据库健康检查通过',
      summary: 'quick_check、schema 与表计数均正常。',
      occurredAt: '2026-03-28T08:26:00.000Z',
      outputPath: '',
      backupPath: '',
      itemNames: [],
      errors: [],
      extra: {
        schemaVersion: 6,
        itemCount: 15,
        workflowCount: 2,
        quickCheck: 'ok',
        foreignKeysEnabled: true,
        tableCounts,
      },
    },
    {
      id: 'history-bookmarks',
      action: 'import_bookmarks',
      status: 'warning',
      title: '浏览器收藏夹已部分导入',
      summary: '导入 8 个网址，跳过 2 个重复链接。',
      occurredAt: '2026-03-27T19:42:00.000Z',
      sourcePath: 'C:\\Users\\realfeeling1\\AppData\\Local\\Google\\Chrome\\User Data\\Default\\Bookmarks',
      outputPath: '',
      backupPath: '',
      itemNames: ['GitHub', 'Linear', 'Notion'],
      errors: ['跳过重复网址：https://github.com', '跳过重复网址：https://linear.app'],
      extra: {
        previewValidCount: 8,
        previewInvalidCount: 0,
        warningCount: 2,
        tableCounts,
      },
    },
  ],
  uiSettings: {
    defaultWorkflowId: 'workflow-focus',
    autoBackupEnabled: true,
    autoBackupIntervalHours: 24,
    backupRetentionCount: 7,
    diagnosticMode: false,
    lastAutoBackupAt: '2026-03-28T08:20:00.000Z',
    overviewSectionOrder: ['recent', 'favorites', 'workflows', 'library'],
    overviewHiddenSections: [],
    overviewLayoutTemplates: [
      {
        id: 'layout-release-demo',
        name: '发布演示',
        sectionOrder: ['recent', 'favorites', 'workflows', 'library'],
        hiddenSections: [],
      },
    ],
    overviewWorkflowLinkMode: 'prioritize_workflows',
  },
}
