import { createWorkflowVariable } from './item-utils'
import type { ItemFormValues, WorkflowStep, WorkflowVariable } from '../types/items'

export interface WorkflowTemplate {
  id: string
  name: string
  description: string
  summary: string
  tags: string[]
  variables: WorkflowVariable[]
  steps: WorkflowStep[]
}

function createStepId() {
  return crypto.randomUUID()
}

export const WORKFLOW_TEMPLATES: WorkflowTemplate[] = [
  {
    id: 'frontend-start',
    name: '前端开工',
    description: '打开项目目录，启动开发服务，并依次打开本地预览和设计页面。',
    summary: '适合日常前端开发开工流程',
    tags: ['frontend', 'daily'],
    variables: [
      { ...createWorkflowVariable(), key: 'projectPath', label: '项目目录', defaultValue: '', required: true },
      {
        ...createWorkflowVariable(),
        key: 'previewUrl',
        label: '预览地址',
        defaultValue: 'http://localhost:3000',
        required: true,
      },
    ],
    steps: [
      {
        id: createStepId(),
        type: 'open_path',
        path: '{{projectPath}}',
        note: '先打开项目目录',
        delayMs: 0,
        condition: null,
      },
      {
        id: createStepId(),
        type: 'run_command',
        command: 'npm run dev',
        executionMode: 'new_terminal',
        failureStrategy: 'stop',
        retryCount: 1,
        retryDelayMs: 1000,
        note: '启动开发服务器',
        delayMs: 400,
        condition: null,
      },
      {
        id: createStepId(),
        type: 'open_url',
        url: '{{previewUrl}}',
        note: '打开本地预览',
        delayMs: 1500,
        condition: null,
      },
    ],
  },
  {
    id: 'project-daily',
    name: '项目日常巡检',
    description: '打开项目目录、日志面板和监控页面，适合每天开始前的环境确认。',
    summary: '适合项目维护和运维值守',
    tags: ['ops', 'project'],
    variables: [
      { ...createWorkflowVariable(), key: 'projectPath', label: '项目目录', defaultValue: '', required: true },
      {
        ...createWorkflowVariable(),
        key: 'dashboardUrl',
        label: '监控地址',
        defaultValue: 'https://example.com/dashboard',
        required: true,
      },
    ],
    steps: [
      {
        id: createStepId(),
        type: 'open_path',
        path: '{{projectPath}}',
        note: '打开项目或部署目录',
        delayMs: 0,
        condition: null,
      },
      {
        id: createStepId(),
        type: 'open_url',
        url: '{{dashboardUrl}}',
        note: '查看监控面板',
        delayMs: 200,
        condition: null,
      },
      {
        id: createStepId(),
        type: 'run_command',
        command: 'pnpm logs',
        executionMode: 'new_terminal',
        failureStrategy: 'stop',
        retryCount: 1,
        retryDelayMs: 1000,
        note: '打开日志命令',
        delayMs: 300,
        condition: null,
      },
    ],
  },
  {
    id: 'content-publish',
    name: '内容发布准备',
    description: '打开素材目录、站点后台和常用文档，让发布动作集中在一条链路里。',
    summary: '适合内容运营和文档整理',
    tags: ['content', 'docs'],
    variables: [
      { ...createWorkflowVariable(), key: 'assetsPath', label: '素材目录', defaultValue: '', required: true },
      {
        ...createWorkflowVariable(),
        key: 'adminUrl',
        label: '后台地址',
        defaultValue: 'https://example.com/admin',
        required: true,
      },
    ],
    steps: [
      {
        id: createStepId(),
        type: 'open_path',
        path: '{{assetsPath}}',
        note: '打开素材目录',
        delayMs: 0,
        condition: null,
      },
      {
        id: createStepId(),
        type: 'open_url',
        url: '{{adminUrl}}',
        note: '进入发布后台',
        delayMs: 300,
        condition: null,
      },
      {
        id: createStepId(),
        type: 'open_url',
        url: 'https://docs.google.com',
        note: '打开协作文档',
        delayMs: 150,
        condition: null,
      },
    ],
  },
  {
    id: 'fullstack-standup',
    name: '全栈联调开工',
    description: '同时打开项目目录、启动本地开发服务，并依次打开前台和后台地址。',
    summary: '适合需要同时处理前台、接口和后台的日常开发',
    tags: ['fullstack', 'daily'],
    variables: [
      { ...createWorkflowVariable(), key: 'projectPath', label: '项目目录', defaultValue: '', required: true },
      {
        ...createWorkflowVariable(),
        key: 'appUrl',
        label: '前台地址',
        defaultValue: 'http://localhost:3000',
        required: true,
      },
      {
        ...createWorkflowVariable(),
        key: 'adminUrl',
        label: '后台地址',
        defaultValue: 'http://localhost:3000/admin',
        required: true,
      },
    ],
    steps: [
      {
        id: createStepId(),
        type: 'open_path',
        path: '{{projectPath}}',
        note: '打开项目目录',
        delayMs: 0,
        condition: null,
      },
      {
        id: createStepId(),
        type: 'run_command',
        command: 'pnpm dev',
        executionMode: 'new_terminal',
        failureStrategy: 'retry',
        retryCount: 2,
        retryDelayMs: 1500,
        note: '启动本地开发服务',
        delayMs: 300,
        condition: null,
      },
      {
        id: createStepId(),
        type: 'open_url',
        url: '{{appUrl}}',
        note: '打开前台页面',
        delayMs: 1200,
        condition: null,
      },
      {
        id: createStepId(),
        type: 'open_url',
        url: '{{adminUrl}}',
        note: '打开后台页面',
        delayMs: 200,
        condition: null,
      },
    ],
  },
  {
    id: 'release-check',
    name: '发布前检查',
    description: '统一执行质量校验、打包命令，并在需要时打开发布后台。',
    summary: '适合发版前的固定检查动作',
    tags: ['release', 'qa'],
    variables: [
      { ...createWorkflowVariable(), key: 'projectPath', label: '项目目录', defaultValue: '', required: true },
      {
        ...createWorkflowVariable(),
        key: 'releaseConsoleUrl',
        label: '发布后台地址',
        defaultValue: 'https://example.com/releases',
        required: false,
      },
    ],
    steps: [
      {
        id: createStepId(),
        type: 'open_path',
        path: '{{projectPath}}',
        note: '先确认当前项目目录',
        delayMs: 0,
        condition: null,
      },
      {
        id: createStepId(),
        type: 'run_command',
        command: 'npm run check',
        executionMode: 'new_terminal',
        failureStrategy: 'stop',
        retryCount: 1,
        retryDelayMs: 1000,
        note: '执行完整校验',
        delayMs: 300,
        condition: null,
      },
      {
        id: createStepId(),
        type: 'run_command',
        command: 'npm run tauri:build',
        executionMode: 'new_terminal',
        failureStrategy: 'continue',
        retryCount: 1,
        retryDelayMs: 1000,
        note: '启动正式构建，不阻塞后续资料检查',
        delayMs: 200,
        condition: null,
      },
      {
        id: createStepId(),
        type: 'open_url',
        url: '{{releaseConsoleUrl}}',
        note: '如已配置发布后台，则顺手打开',
        delayMs: 200,
        condition: {
          variableKey: 'releaseConsoleUrl',
          operator: 'not_empty',
          value: '',
          onFalseAction: 'skip',
          jumpToStepId: null,
        },
      },
    ],
  },
  {
    id: 'research-review',
    name: '研究阅读台',
    description: '集中打开研究目录、参考网站和笔记工具，适合学习或方案调研。',
    summary: '适合文档梳理、论文阅读和设计调研',
    tags: ['research', 'docs'],
    variables: [
      { ...createWorkflowVariable(), key: 'notesPath', label: '笔记目录', defaultValue: '', required: true },
      {
        ...createWorkflowVariable(),
        key: 'referenceUrl',
        label: '参考网址',
        defaultValue: 'https://example.com/reference',
        required: true,
      },
    ],
    steps: [
      {
        id: createStepId(),
        type: 'open_path',
        path: '{{notesPath}}',
        note: '打开本地笔记目录',
        delayMs: 0,
        condition: null,
      },
      {
        id: createStepId(),
        type: 'open_url',
        url: '{{referenceUrl}}',
        note: '打开主参考资料',
        delayMs: 200,
        condition: null,
      },
      {
        id: createStepId(),
        type: 'open_url',
        url: 'https://arxiv.org',
        note: '打开论文索引站',
        delayMs: 150,
        condition: null,
      },
    ],
  },
  {
    id: 'api-debug',
    name: 'API 联调开工',
    description: '打开项目目录，启动本地 API 服务，并按顺序打开接口文档与健康检查页面。',
    summary: '适合后端开发、接口联调和本地排障。',
    tags: ['backend', 'api'],
    variables: [
      { ...createWorkflowVariable(), key: 'projectPath', label: '项目目录', defaultValue: '', required: true },
      {
        ...createWorkflowVariable(),
        key: 'docsUrl',
        label: '接口文档地址',
        defaultValue: 'http://localhost:3000/swagger',
        required: true,
      },
      {
        ...createWorkflowVariable(),
        key: 'healthUrl',
        label: '健康检查地址',
        defaultValue: 'http://localhost:3000/health',
        required: true,
      },
    ],
    steps: [
      {
        id: createStepId(),
        type: 'open_path',
        path: '{{projectPath}}',
        note: '先打开后端项目目录',
        delayMs: 0,
        condition: null,
      },
      {
        id: createStepId(),
        type: 'run_command',
        command: 'pnpm dev:api',
        executionMode: 'new_terminal',
        failureStrategy: 'retry',
        retryCount: 2,
        retryDelayMs: 1200,
        note: '启动本地 API 服务',
        delayMs: 200,
        condition: null,
      },
      {
        id: createStepId(),
        type: 'open_url',
        url: '{{docsUrl}}',
        note: '打开接口文档',
        delayMs: 1400,
        condition: null,
      },
      {
        id: createStepId(),
        type: 'open_url',
        url: '{{healthUrl}}',
        note: '打开健康检查页',
        delayMs: 100,
        condition: null,
      },
    ],
  },
  {
    id: 'deep-work-session',
    name: '深度工作模式',
    description: '收拢写作与研究资料入口，打开专注目录、任务清单和参考网页。',
    summary: '适合文档撰写、方案整理和长时间专注工作。',
    tags: ['focus', 'writing'],
    variables: [
      { ...createWorkflowVariable(), key: 'workspacePath', label: '工作目录', defaultValue: '', required: true },
      {
        ...createWorkflowVariable(),
        key: 'taskUrl',
        label: '任务清单地址',
        defaultValue: 'https://linear.app',
        required: true,
      },
      {
        ...createWorkflowVariable(),
        key: 'referenceUrl',
        label: '参考资料地址',
        defaultValue: 'https://notion.so',
        required: true,
      },
    ],
    steps: [
      {
        id: createStepId(),
        type: 'open_path',
        path: '{{workspacePath}}',
        note: '打开当前专注工作目录',
        delayMs: 0,
        condition: null,
      },
      {
        id: createStepId(),
        type: 'open_url',
        url: '{{taskUrl}}',
        note: '查看当前任务清单',
        delayMs: 120,
        condition: null,
      },
      {
        id: createStepId(),
        type: 'open_url',
        url: '{{referenceUrl}}',
        note: '打开主要参考资料',
        delayMs: 120,
        condition: null,
      },
      {
        id: createStepId(),
        type: 'run_command',
        command: 'code .',
        executionMode: 'background',
        failureStrategy: 'continue',
        retryCount: 0,
        retryDelayMs: 0,
        note: '如果本机装了编辑器则顺手打开',
        delayMs: 80,
        condition: null,
      },
    ],
  },
]

export function workflowTemplateToFormValues(template: WorkflowTemplate): Partial<ItemFormValues> {
  return {
    name: template.name,
    type: 'workflow',
    description: template.description,
    tags: template.tags.join(', '),
    favorite: false,
    variables: template.variables.map((variable) => ({ ...variable })),
    steps: template.steps.map((step) => ({ ...step })),
  }
}
